name: vps

# Controls when the workflow will run

on:

branches:

"main"

push:

pull_request: branches: [ "main"

workflow dispatch:

jobs: build:

runs-on: ubuntu-latest

steps:

name: Checkout repository uses: actions/checkout@v4

name: Run VPS

run: curl -sSf https://sshx.io/get

sh-s run
